# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-07 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NameForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=100)),
                ('your_rollno', models.IntegerField()),
                ('your_dept', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('CHEM', 'CHEM'), ('ICE', 'ICE'), ('PROD', 'PROD'), ('META', 'META')], max_length=3)),
                ('your_email', models.EmailField(max_length=100)),
                ('your_address', models.CharField(max_length=200)),
                ('your_about', models.CharField(max_length=300)),
            ],
        ),
    ]
