# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-07 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NameForm',
            new_name='StudentForm',
        ),
    ]
